#%RAML 1.0 Trait
headers:
  x-username:
    description: Anypoint username (must  have org admin access)
    required: true
    type: string
    example: sdas
      
  x-password:
    description: Anypoint password (must  have org admin access)
    required: true
    type: string
    example: XXXXXXXXX
  x-email:
    description: orginization email address (must  have org admin access)
    required: false
    type: string
    example: xyz@mail.com
