#%RAML 1.0 NamedExample
-
 env: dev
 runtime :
    - 
     mule_ver: "4.1.6"
     support_endby: 2020-11-03
    - 
     mule_ver: "4.3.0"
     support_endby: 2022-11-02
-
 env: st
 runtime :
    - 
     mule_ver: "4.2.2"
     support_endby: 2020-11-03
    - 
     mule_ver: "4.3.0"
     support_endby: 2021-05-03